import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import type { Plugin } from 'vite';
import type { OutputBundle } from 'rolldown';

const STATIC_PUBLIC_PATHS = [
  '/manifest.webmanifest',
  '/favicon.svg',
  '/helm-mark.svg',
  '/icons/icon-180.png',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-512-maskable.png'
];

function bundleDigest(bundle: OutputBundle, projectRoot = ''): string {
  const hash = createHash('sha256');
  Object.keys(bundle).sort().forEach((fileName) => {
    const item = bundle[fileName];
    hash.update(fileName);
    hash.update(item.type);
    if (item.type === 'chunk') {
      hash.update(item.code);
    } else if (typeof item.source === 'string') {
      hash.update(item.source);
    } else {
      hash.update(Buffer.from(item.source));
    }
  });
  STATIC_PUBLIC_PATHS.forEach((publicPath) => {
    hash.update(publicPath);
    if (!projectRoot) return;
    try {
      hash.update(readFileSync(join(projectRoot, 'public', publicPath.slice(1))));
    } catch {
      // Missing optional public assets are reported by the worker's required
      // precache validation; keep digest generation resilient here.
    }
  });
  return hash.digest('hex').slice(0, 12);
}

function serviceWorkerSource(cacheName: string, precacheUrls: string[]): string {
  return `/* Helm offline shell — generated by Vite. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = Object.freeze(${JSON.stringify(precacheUrls)});
const SHELL_URLS = Object.freeze(['/index.html', '/']);
const MAX_RETAINED_CACHES = 3;
const NEVER_CACHE_PREFIXES = ['/api/', '/auth/', '/login', '/logout', '/cdn-cgi/'];

function sameOrigin(value) {
  try {
    return new URL(value, self.location.origin).origin === self.location.origin;
  } catch {
    return false;
  }
}

function isNeverCachePath(pathname) {
  return NEVER_CACHE_PREFIXES.some((prefix) => pathname === prefix.slice(0, -1) || pathname.startsWith(prefix));
}

function validStaticResponse(response, requestUrl, expectHtml) {
  if (!response || !response.ok || response.redirected || response.type === 'opaque') return false;
  const expectedUrl = new URL(requestUrl, self.location.origin);
  const responseUrl = new URL(response.url || requestUrl, self.location.origin);
  if (!sameOrigin(responseUrl.href) || responseUrl.origin !== expectedUrl.origin) return false;
  if (responseUrl.pathname !== expectedUrl.pathname) return false;
  const contentType = (response.headers.get('content-type') || '').toLowerCase();
  if (expectHtml) return contentType.includes('text/html');
  return !contentType.includes('text/html');
}

async function validShellResponse(response, requestUrl) {
  if (!validStaticResponse(response, requestUrl, true)) return false;
  const html = await response.clone().text();
  // The app mount and a module script make this recognisably Helm's shell;
  // common auth-page markers keep a login response out of the offline cache.
  if (!/<[^>]+id=["']app["']/i.test(html) || !/<script\\b[^>]+src=/i.test(html)) return false;
  if (/(?:\\/login\\b|\\/sign-in\\b|\\bsign[ -]?in\\b|\\blog[ -]?in\\b|\\bauthenticate\\b)/i.test(html)) return false;
  return true;
}

function cacheKey(url) {
  return new Request(new URL(url).origin + new URL(url).pathname, { method: 'GET' });
}

async function cachePrecacheEntry(cache, pathname) {
  const url = new URL(pathname, self.location.origin);
  const request = new Request(url.href, {
    cache: 'reload',
    credentials: 'same-origin',
    redirect: 'error'
  });
  const response = await fetch(request);
  const valid = pathname === '/' || pathname === '/index.html'
    ? await validShellResponse(response, url.href)
    : validStaticResponse(response, url.href, false);
  if (!valid) throw new Error('response validation failed');
  await cache.put(cacheKey(url.href), response.clone());
}

async function preparePrecache() {
  const cache = await caches.open(CACHE_NAME);
  const failures = [];
  for (const pathname of PRECACHE_URLS) {
    try {
      await cachePrecacheEntry(cache, pathname);
    } catch {
      failures.push(pathname);
    }
  }
  if (failures.length) {
    // Never activate a partial shell. The currently active worker/cache stays
    // in place while this build retries its required static responses.
    await caches.delete(CACHE_NAME);
    throw new Error('required static precache validation failed');
  }
}

async function missingPrecacheEntries(cache) {
  const missing = [];
  for (const pathname of PRECACHE_URLS) {
    const response = await cache.match(cacheKey(new URL(pathname, self.location.origin).href));
    const valid = pathname === '/' || pathname === '/index.html'
      ? response && await validShellResponse(response, pathname)
      : response && validStaticResponse(response, pathname, false);
    if (!valid) missing.push(pathname);
  }
  return missing;
}

async function shellStatus() {
  const cache = await caches.open(CACHE_NAME);
  let missing = await missingPrecacheEntries(cache);
  if (missing.length) {
    // Cache storage can be evicted while the worker registration survives.
    // Repair only missing entries; never discard a healthy active cache.
    for (const pathname of missing) {
      try {
        await cachePrecacheEntry(cache, pathname);
      } catch {
        // A later online status request can retry this individual entry.
      }
    }
    missing = await missingPrecacheEntries(cache);
    if (missing.length) return { shellCached: false, error: 'Offline shell is incomplete; static assets will be retried online.' };
  }
  for (const pathname of SHELL_URLS) {
    const response = await cache.match(cacheKey(new URL(pathname, self.location.origin).href));
    if (response && await validShellResponse(response, pathname)) {
      return { shellCached: true, error: '' };
    }
  }
  return { shellCached: false, error: 'The static app shell could not be cached.' };
}

async function sendShellStatus(client) {
  try {
    const status = await shellStatus();
    client?.postMessage({ type: status.error ? 'PWA_CACHE_ERROR' : 'PWA_CACHE_READY', ...status });
  } catch {
    client?.postMessage({ type: 'PWA_CACHE_ERROR', shellCached: false, error: 'Offline shell status is unavailable.' });
  }
}

async function broadcastShellStatus() {
  try {
    const status = await shellStatus();
    const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    windows.forEach((client) => client.postMessage({ type: status.error ? 'PWA_CACHE_ERROR' : 'PWA_CACHE_READY', ...status }));
  } catch {
    const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    windows.forEach((client) => client.postMessage({ type: 'PWA_CACHE_ERROR', shellCached: false, error: 'Offline shell status is unavailable.' }));
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(preparePrecache());
  // Do not call skipWaiting here. Updates remain reviewable until the app's
  // explicit update action sends the user-approved message below.
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    const appCaches = names.filter((name) => name.startsWith('helm-static-v'));
    const keep = new Set([
      CACHE_NAME,
      ...appCaches.filter((name) => name !== CACHE_NAME).reverse().slice(0, MAX_RETAINED_CACHES - 1)
    ]);
    await Promise.all(appCaches.filter((name) => !keep.has(name)).map((name) => caches.delete(name)));
    // Claim is safe for initial activation and does not activate a waiting
    // update; the update still requires the message handler's consent.
    await self.clients.claim();
    await broadcastShellStatus();
  })());
});

self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data.type === 'PWA_STATUS') {
    event.waitUntil(sendShellStatus(event.source));
  }
});

function isKnownAssetPath(pathname) {
  if (isNeverCachePath(pathname)) return false;
  return pathname.startsWith('/assets/')
    || pathname.startsWith('/icons/')
    || pathname === '/manifest.webmanifest'
    || pathname === '/favicon.svg'
    || pathname === '/helm-mark.svg';
}

async function networkFirstNavigation(request) {
  try {
    // A response with 401/403/5xx is still a network response and must be
    // returned as-is; only a rejected fetch is eligible for shell fallback.
    return await fetch(request);
  } catch {
    const cache = await caches.open(CACHE_NAME);
    for (const pathname of SHELL_URLS) {
      const response = await cache.match(cacheKey(new URL(pathname, self.location.origin).href));
      if (response && await validShellResponse(response, pathname)) {
        // navigator.onLine can remain true after a cached navigation (and
        // during captive-portal outages). Mark this known shell so the app
        // starts read-only even with no private snapshot saved yet.
        const html = (await response.text()).replace('</head>', '<meta name="helm-offline-shell" content="true"></head>');
        const headers = new Headers(response.headers);
        headers.delete('content-length');
        headers.delete('content-encoding');
        headers.set('cache-control', 'no-store');
        return new Response(html, { status: 200, headers });
      }
    }
    return Response.error();
  }
}

async function cacheFirstAsset(request, event) {
  const url = new URL(request.url);
  const key = cacheKey(url.href);
  const cache = await caches.open(CACHE_NAME);
  const appCacheNames = [
    CACHE_NAME,
    ...(await caches.keys())
      .filter((name) => name.startsWith('helm-static-v') && name !== CACHE_NAME)
      .reverse()
  ];
  let cached;
  for (const name of appCacheNames) {
    const candidate = await caches.open(name).then((candidateCache) => candidateCache.match(key));
    if (candidate && validStaticResponse(candidate, url.href, false)) {
      cached = candidate;
      break;
    }
  }
  if (cached) return cached;
  await cache.delete(key);
  try {
    // Static assets may sit behind same-origin access control. Keep the
    // authenticated fetch, but persist only the credential-free URL key and
    // a validated static response; API/auth responses never reach this path.
    const staticRequest = new Request(request, { cache: 'no-store', credentials: 'same-origin' });
    const response = await fetch(staticRequest);
    if (PRECACHE_URLS.includes(url.pathname) && validStaticResponse(response, url.href, false)) {
      event.waitUntil(cache.put(key, response.clone()));
    }
    return response;
  } catch {
    return cached || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || isNeverCachePath(url.pathname)) return;
  if (request.mode === 'navigate') {
    event.respondWith(networkFirstNavigation(request));
  } else if (isKnownAssetPath(url.pathname)) {
    event.respondWith(cacheFirstAsset(request, event));
  }
});
`;
}

function pwaServiceWorker(): Plugin {
  let projectRoot = '';
  return {
    name: 'helm-pwa-service-worker',
    apply: 'build',
    configResolved(config) {
      projectRoot = config.root;
    },
    generateBundle(_options, bundle) {
      const generatedAssets = Object.keys(bundle)
        .filter((fileName) => fileName !== 'sw.js' && !fileName.endsWith('.map'))
        .map((fileName) => `/${fileName}`);
      const precacheUrls = Array.from(new Set([
        '/',
        '/index.html',
        ...generatedAssets,
        ...STATIC_PUBLIC_PATHS
      ])).sort();
      const digest = bundleDigest(bundle, projectRoot);
      const requestedVersion = process.env.HELM_BUILD_VERSION?.replace(/[^a-zA-Z0-9._-]/g, '-');
      const buildVersion = `${requestedVersion || Date.now().toString(36)}-${digest}`;
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorkerSource(`helm-static-v${buildVersion}`, precacheUrls)
      });
    }
  };
}

export default defineConfig({
  plugins: [svelte(), pwaServiceWorker()],
  server: {
    port: 5173,
    host: true
  },
  preview: {
    port: 4173,
    host: true
  }
});
